### ISSUE TITLE
Licencia?

### ISSUE THREAD

**Issue by jazzido** [xavierlesa/pymarketapi#1]
Hola,

Bajo qué licencia tenés pensado liberar el código? [Reacomodé el código para empaquetarlo en un Python Egg](https://github.com/jazzido/pymarketapi), pero estaría bueno saber con qué licencia está publicado tu código para saber qué puedo hacer con el :)

Avisame cuando elijas una licencia así te mando un pull request con los cambios que hice.

Saludos!

**Comment by xavierlesa** [comment]
Listo!
También agregué el empaquetado, gracias por la recomendación.

Saludos
